FROM node:18

# Install dependencies
RUN apt-get update && \
    apt-get install -y ffmpeg python3-pip && \
    pip3 install yt-dlp

# Create app directory
WORKDIR /app
COPY . .

RUN npm install

EXPOSE 3000

CMD [ "npm", "start" ]
